name: Lighthouse CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Snapshot RSS
        run: npm run rss:snapshot

      - name: Build
        run: npm run build

      - name: Run Lighthouse CI
        run: npx lhci autorun --upload.target=temporary-public-storage
